syntax = "proto3";

package securities.transactional.datafeed.consumer.entity.v1;

import "securities/transactional/datafeed/v1/best_bid_offer.proto";

option java_package = "com.stockbit.protobuf.securities.transactional.datafeed.consumer.entity.v1.datafeed";
option java_multiple_files = true;

enum HotlistType {
  HOTLIST_TYPE_UNSPECIFIED = 0;
  HOTLIST_TYPE_TOP_GAINER = 1;
  HOTLIST_TYPE_TOP_LOSER = 2;
  HOTLIST_TYPE_MOST_ACTIVE = 3;
}

enum BoardType {
  BOARD_TYPE_UNSPECIFIED = 0;
  BOARD_TYPE_RG = 1;
  BOARD_TYPE_TN = 2;
  BOARD_TYPE_NG = 3;
}

message Change {
  double value = 1;
  double percentage = 2;
}

message Company {
  string symbol = 1;
  string symbol2 = 2;
  string symbol3 = 3;
  string name = 4;
  int64 sector = 5;
  int64 sub_sector = 6 [json_name = "sub_sector"];
  string type = 7;
  double latest_price = 8 [json_name = "latest_price"];
  double latest_numshare = 9 [json_name = "latest_numshare"];
  string country = 10;
  string exchange = 11;
  string default_currency = 12 [json_name = "default_currency"];
  string tz = 13;
  string trade_type = 14 [json_name = "trade_type"];
  string isin = 15;
  string sedol = 16;
  int32 status = 17;
  int32 tradable = 18;
  string sector_name = 19 [json_name = "sector_name"];
  string sub_sector_name = 20 [json_name = "sub_sector_name"];
}

message Sector {
  int64 id = 1;
  string name = 2;
  int64 parent = 3;
  int32 disabled = 4;
  string alias1 = 5;
  string alias2 = 6;
  int64 market_id = 7 [json_name = "market_id"];
  int64 global_sector_id = 8 [json_name = "global_sector_id"];
  string parent_name = 9 [json_name = "parent_name"];
}

message Hotlist {
  repeated string stocks = 1;
  HotlistType type = 2;
}

message Intraday {
  string stock_code = 1 [json_name = "stock_code"];
  string datetime = 2;
  double open = 3;
  double high = 4;
  double low = 5;
  double close = 6;
  double volume = 7;
  Change change = 8;
}

message LivePrice {
  string stock_code = 1 [json_name = "stock_code"];
  double lastprice = 2;
  double volume = 3;
  double high = 4;
  double low = 5;
  double open = 6;
  double frequency = 7;
  double frg_buy = 8 [json_name = "frg_buy"];
  double frg_sell = 9 [json_name = "frg_sell"];
  double average = 10;
  string date = 11;
  double close = 12;
  double prev = 13;
  double value = 14;
  Change change = 15;
  string order_verb = 16 [json_name = "order_verb"];
  int64 quantity = 17;
  bool is_index = 18 [json_name = "is_index"];
  int64 sequence_number = 19 [json_name = "sequence_number"];
  int64 order_book_id = 20 [json_name = "order_book_id"];
  int64 order_number = 21 [json_name = "order_number"];
  int64 match_number = 22 [json_name = "match_number"];
  BoardType board = 23;
}

message Orderbook {
  string stock_code = 1 [json_name = "stock_code"];
  string body = 2;
  int64 sequence_number = 3 [json_name = "sequence_number"];
  int64 order_book_id = 4 [json_name = "order_book_id"];
  // datetime : RFC3339Nano, 2022-12-07T13:37:13.005633+07:00, formatted time from itch timestamp
  string datetime = 5;
}

message IepIev {
  string stock_code = 1 [json_name = "stock_code"];
  double iep = 2;
  double iev = 3;
  int64 sequence_number = 4 [json_name = "sequence_number"];
  string datetime = 5;
  securities.transactional.datafeed.v1.BestBidOffer best_bid_offer = 6 [json_name = "best_bid_offer"];
}
