// Copyright (c) 2021-2024 Stockbit All rights reserved.

syntax = "proto3";

package platform.websocket.wsevent.v1;

import "google/protobuf/timestamp.proto";
import "platform/websocket/wsevent/v1/auth.proto";
import "platform/websocket/wsevent/v1/ping.proto";
import "securities/trm/core/portfolio/wsevent/v1/securities.proto";

option go_package = "go.stockbit.io/protos/gen/go/platform/websocket/wsevent/v1;websocket";

// Please refer this docs for it's usage
// https://www.notion.so/stockbit/Using-Gen-Websocket-dc8ea00f6cdd4491b2577dbcfed481fa?pvs=4

// WebsocketRequest handles request for communicating via websocket
message WebsocketRequest {
  message Request {
    enum Command {
      COMMAND_UNSPECIFIED = 0;
      COMMAND_PING = 1;
      COMMAND_AUTH = 2;
    }
    enum Channel {
      CHANNEL_UNSPECIFIED = 0;
      CHANNEL_SECURITIES_LIVE_PORTO = 1;
      CHANNEL_NEGO_ENGINE_ORDER_BOOK = 2;
    }
    bytes value = 1;
    oneof action {
      Command command = 2;
      Channel subscribe = 3;
      Channel unsubscribe = 4;
    }
  }
  repeated Request requests = 1;
}

// WebsocketResponse handles response for communicating via websocket
message WebsocketResponse {
  google.protobuf.Timestamp timestamp = 1;
  // message_channel contains possible ws event can be sent into client
  oneof response {
    PingResponse ping = 2; // to accommodate PING PONG event
    AuthResponse auth = 3; // to accommodate re-authentication via ws event
    securities.trm.core.portfolio.wsevent.v1.WebsocketResponse securities = 4; // to accommodate securities-related ws response
  }
}
