// Copyright (c) 2021-2025 Stockbit All rights reserved.

syntax = "proto3";

package securities.transactional.negoengine.entity.v1;

option go_package = "go.stockbit.io/protos/gen/go/securities/transactional/negoengine/entity/v1;entityv1pb";

// **Asset** defines the minimal canonical reference needed to identify a traded
// instrument for the Nego Engine.
message Asset {
  // **Code** of the instrument.
  // - Must not be empty. Uppercase alphanumerics and dashes are common
  //   conventions (see examples in [AssetType]).
  // - Must be between 4 to 24 characters long.
  //
  // Examples: "BBCA", "BBRI-R", "BIPI-W2".
  string code = 1;

  // **Canonical asset type.** Must be one of the defined enum values.
  AssetType type = 2;
}

// **AssetType** enumerates supported instrument classifications so the service
// can apply the right business rules.
enum AssetType {
  // Unspecified asset type. Not allowed.
  ASSET_TYPE_UNSPECIFIED = 0;

  // Regular equity ticker, usually 4 uppercase letters.
  //
  // Example codes: "BBCA", "BBRI", "TLKM".
  ASSET_TYPE_STOCK_REGULAR = 1;

  // Stock that is categorized as watchlist type.
  ASSET_TYPE_STOCK_WATCHLIST = 2;

  // Stock that is categorized as acceleration type.
  ASSET_TYPE_STOCK_ACCELERATION = 3;

  // Rights issue (HMETD) for an equity, commonly with "-R" suffix.
  //
  // Example code: "BBRI-R" (suffix "-R").
  ASSET_TYPE_STOCK_RIGHT = 4;

  // Equity warrant, commonly equity ticker with "-W" (or "-W", "-W2", etc.) suffix.
  //
  // Example codes: "BIPI-W2", "TRAM-W" (suffix "-W", optionally numbered).
  ASSET_TYPE_STOCK_WARRANT = 5;

  // Structured warrant, commonly have more than 7 characters.
  //
  // Example codes: "BBCAYUCH5A", "ANTMDRCH5A".
  ASSET_TYPE_STOCK_STRUCTURED_WARRANT = 6;

  // Mutual fund product, usually an ETF and has a prefix of "X".
  //
  // Example code: "XSBC".
  ASSET_TYPE_MUTUAL_FUND = 7;
}
