// Copyright (c) 2021-2024 Stockbit All rights reserved.

syntax = "proto3";

package securities.trm.core.portfolio.wsevent.v1;

import "securities/transactional/negoengine/order_book/entity/v1/order_book.proto";
import "securities/trm/core/portfolio/entity/v2/portfolio.proto";

option go_package = "go.stockbit.io/protos/gen/go/securities/trm/core/portfolio/wsevent/v1;portowsevent";

// WebsocketResponse defines messages when sending response to websocket client
message WebsocketResponse {
  // Action provides various action can applied to websocket message
  enum Action {
    ACTION_UNSPECIFIED = 0;
    ACTION_UPSERT = 1; // act message_channel as updated or inserted
    ACTION_DELETE = 2; // act message_channel as deleted
  }
  message OrderList {
    repeated securities.trm.core.portfolio.entity.v2.Order orders = 1;
    repeated securities.trm.core.portfolio.entity.v2.Order orders_v2 = 2; // v2 contains v1 + new corpact of orders
  }
  Action action = 1; // specify action applied for message
  oneof message {
    securities.trm.core.portfolio.entity.v2.PortfolioSummary portfolio_summary = 2;
    securities.trm.core.portfolio.entity.v2.PortfolioDetail portfolio_detail = 3;
    securities.trm.core.portfolio.entity.v2.PortfolioList portfolio_list = 4;
    securities.trm.core.portfolio.entity.v2.Order order_detail = 5;
    OrderList order_list = 6;
    securities.trm.core.portfolio.entity.v2.PortfolioDetail portfolio_detail_day_trade = 7;
    securities.transactional.negoengine.order_book.entity.v1.OrderBook nego_engine_order_book = 8;
  }
  reserved 9 to 15; // for another message type since using oneof operation

  enum Event {
    EVENT_UNSPECIFIED = 0;
    EVENT_NEW_CONNECTION = 1;
    EVENT_NEW_TRANSACTION_UPDATE = 2;
  }
  // event identifies the source that triggered the websocket response
  Event event = 16;
}
