// Copyright (c) 2021-2024 Stockbit All rights reserved.

syntax = "proto3";

package financial.order_trade.entity.v1;

import "financial/order_trade/entity/v1/investor_type.proto";
import "financial/order_trade/entity/v1/running_trade.proto";
import "financial/order_trade/entity/v1/trade_book.proto";

option go_package = "go.stockbit.io/protos/gen/go/financial/order_trade/entity/v1;entity";

enum BrokerGroup {
  BROKER_GROUP_UNSPECIFIED = 0;
  BROKER_GROUP_FOREIGN = 1;
  BROKER_GROUP_GOVERNMENT = 2;
  BROKER_GROUP_LOCAL = 3;
}

// buf:lint:ignore ENUM_VALUE_PREFIX
enum TopBrokerSortBy {
  TB_SORT_BY_UNSPECIFIED = 0;
  TB_SORT_BY_CODE = 1;
  TB_SORT_BY_NAME = 2;
  TB_SORT_BY_GROUP = 3;
  TB_SORT_BY_TOTAL_VALUE = 4;
  TB_SORT_BY_NET_VALUE = 5;
  TB_SORT_BY_BUY_VALUE = 6;
  TB_SORT_BY_SELL_VALUE = 7;
  TB_SORT_BY_TOTAL_VOLUME = 8;
  TB_SORT_BY_TOTAL_FREQUENCY = 9;
}

// buf:lint:ignore ENUM_VALUE_PREFIX
enum TopBrokerPeriod {
  TB_PERIOD_UNSPECIFIED = 0;
  TB_PERIOD_LAST_1_DAY = 1;
  TB_PERIOD_LAST_7_DAYS = 2;
  TB_PERIOD_LAST_1_MONTH = 3;
  TB_PERIOD_LAST_1_YEAR = 4;
  TB_PERIOD_PREVIOUS_DAY = 5;
  TB_PERIOD_YEAR_TO_DATE = 6;
}

enum BrokerDistributionDataType {
  BROKER_DISTRIBUTION_DATA_TYPE_UNSPECIFIED = 0;
  BROKER_DISTRIBUTION_DATA_TYPE_VALUE = 1;
  BROKER_DISTRIBUTION_DATA_TYPE_VOLUME = 2;
}

enum BrokerSummaryPeriod {
  BROKER_SUMMARY_PERIOD_UNSPECIFIED = 0;
  BROKER_SUMMARY_PERIOD_LATEST = 1; // latest idx data 3
  BROKER_SUMMARY_PERIOD_YESTERDAY = 2; // h-1 latest idx data 3
  BROKER_SUMMARY_PERIOD_LAST_7_DAYS = 3;
  BROKER_SUMMARY_PERIOD_THIS_MONTH = 4; // month to date, 1st day to today
  BROKER_SUMMARY_PERIOD_LAST_1_MONTH = 5;
  BROKER_SUMMARY_PERIOD_LAST_3_MONTHS = 6;
  BROKER_SUMMARY_PERIOD_LAST_6_MONTHS = 7;
  BROKER_SUMMARY_PERIOD_YEAR_TO_DATE = 8;
  BROKER_SUMMARY_PERIOD_LAST_1_YEAR = 9;
  BROKER_SUMMARY_PERIOD_PREVIOUS_MONTH = 10;
}

message TopBroker {
  string code = 1;
  string name = 2;
  financial.order_trade.entity.v1.InvestorType investor_type = 3 [json_name = "investor_type"];
  int64 total_value = 4 [json_name = "total_value"];
  int64 net_value = 5 [json_name = "net_value"];
  int64 buy_value = 6 [json_name = "buy_value"];
  int64 sell_value = 7 [json_name = "sell_value"];
  int64 total_volume = 8 [json_name = "total_volume"];
  int64 total_frequency = 9 [json_name = "total_frequency"];
  BrokerGroup group = 10;
}

enum TransactionType {
  TRANSACTION_TYPE_UNSPECIFIED = 0;
  TRANSACTION_TYPE_NET = 1;
  TRANSACTION_TYPE_GROSS = 2;
}

message BrokerDetector {
  double average = 1;
  DetailTrxBroker avg = 2;
  DetailTrxBroker avg5 = 3;
  string broker_accdist = 4 [json_name = "broker_accdist"];
  int32 number_broker_buysell = 5 [json_name = "number_broker_buysell"];
  DetailTrxBroker top1 = 6;
  DetailTrxBroker top3 = 7;
  DetailTrxBroker top5 = 8;
  DetailTrxBroker top10 = 9;
  int32 total_buyer = 10 [json_name = "total_buyer"];
  int32 total_seller = 11 [json_name = "total_seller"];
  double value = 12;
  double volume = 13;
}

message DetailTrxBroker {
  string accdist = 1 [json_name = "accdist"];
  double amount = 2;
  double percent = 3;
  double vol = 4;
}

message BrokerTransaction {
  string stock_code = 1 [json_name = "stock_code"];
  string broker_code = 2 [json_name = "broker_code"];
  string type = 3;
  string date = 4;
  double avg_price = 5 [json_name = "avg_price"];
  double net_value = 6 [json_name = "net_value"];
  double gross_buy_value = 7 [json_name = "gross_buy_value"];
  double gross_sell_value = 8 [json_name = "gross_sell_value"];
  double net_lot = 9 [json_name = "net_lot"];
  double gross_buy_volume = 10 [json_name = "gross_buy_volume"];
  double gross_sell_volume = 11 [json_name = "gross_sell_volume"];
}

message BrokerActivity {
  repeated BrokerActivitySummary brokers_buy = 1;
  repeated BrokerActivitySummary brokers_sell = 2;
}

message BrokerActivitySummary {
  string stock_code = 1;
  string broker_code = 2;
  financial.order_trade.entity.v1.BrokerType type = 3;
  string date = 4; // example : "yyyy-mm-dd"
  double value = 5;
  double lot = 6;
  double avg_price = 7;
  double freq = 8;
}

message BrokerDistributionGroup {
  repeated BrokerDistribution top_broker_buy = 1;
  repeated BrokerDistribution top_broker_sell = 2;
}

message BrokerDistribution {
  BrokerDistributionDetail detail = 1;
  repeated BrokerDistributionDetail distribute_to = 2;
}

message BrokerDistributionDetail {
  string code = 1;
  string type = 2;
  double amount = 3;
}

message BrokerActivityChartData {
  TypeChart type = 1;
  repeated string symbols = 2; // ex : ["AALI","BBCA",...]
  repeated BrokerActivityChart charts = 3;
}

message BrokerActivityChart {
  string symbol = 1 [json_name = "symbol"];
  repeated BrokerActivityChartDetail chart = 2;
}

message BrokerActivityChartDetail {
  string date = 1; // ex: "YYYY-MM-DD"
  string time = 2; // ex: "HH:mm"
  Value value = 3;
  string datetime_label = 4 [json_name = "datetime_label"]; // value can be dynamic as HH:mm / YYYY-MM-DD
}
