// Copyright (c) 2021-2024 Stockbit All rights reserved.

syntax = "proto3";

package financial.order_trade.entity.v1;

option go_package = "go.stockbit.io/protos/gen/go/financial/order_trade/entity/v1;entity";

enum GroupBy {
  GROUP_BY_UNSPECIFIED = 0;
  GROUP_BY_PRICE = 1;
  GROUP_BY_TIME = 2;
}

message BookSummary {
  repeated Book book = 1;
  repeated string market_hour_steps = 2 [json_name = "market_hour_steps"]; // ex: ['09:00','09:30','10:00']
  BookTotal book_total = 3 [json_name = "book_total"];
  bool is_show_pre_post = 4 [json_name = "is_show_pre_post"];
  bool is_fca_stock = 5 [json_name = "is_fca_stock"];
}

message Book {
  string price = 1; // ex: 4,030
  Summary buy = 2;
  Summary sell = 3;
  string time = 4; // ex: 09:30
  Summary pre_open = 5 [json_name = "pre_open"];
  Summary post_close = 6 [json_name = "post_close"];
  Summary total = 7;
}

message Summary {
  string lot = 1; // ex: 1,976
  string frequency = 2; // ex: 1,879
  string percentage = 3; // ex: 66%
}

message BookTotal {
  string buy_frequency = 1 [json_name = "buy_frequency"];
  string sell_frequency = 2 [json_name = "sell_frequency"];
  string buy_lot = 3 [json_name = "buy_lot"];
  string sell_lot = 4 [json_name = "sell_lot"];
  string buy_percentage = 5 [json_name = "buy_percentage"];
  string sell_percentage = 6 [json_name = "sell_percentage"];
  string total_frequency = 7 [json_name = "total_frequency"];
  string total_lot = 8 [json_name = "total_lot"];
  string pre_lot = 9 [json_name = "pre_lot"];
  string post_lot = 10 [json_name = "post_lot"];
  string pre_frequency = 11 [json_name = "pre_frequency"];
  string post_frequency = 12 [json_name = "post_frequency"];
}

message BookChart {
  repeated Chart buy = 1;
  repeated Chart sell = 2;
  Chart pre_post = 3 [json_name = "pre_post"];
  bool is_show_pre_post = 4 [json_name = "is_show_pre_post"];
  bool is_fca_stock = 5 [json_name = "is_fca_stock"];
}

message Chart {
  Value frequency = 1;
  Value lot = 2;
  string time = 3; // ex: "09:30"
}

message Value {
  int64 raw = 1; // ex: 1879
  string formatted = 2; // ex: 1,88K
}
