jadx.core.utils.exceptions.JadxRuntimeException: Failed to generate code for class: androidx.camera.core.impl.InterfaceC2263h0
	at jadx.core.ProcessClass.generateCode(ProcessClass.java:123)
	at jadx.core.dex.nodes.ClassNode.generateClassCode(ClassNode.java:401)
	at jadx.core.dex.nodes.ClassNode.decompile(ClassNode.java:389)
	at jadx.core.dex.nodes.ClassNode.getCode(ClassNode.java:339)
Caused by: java.lang.OutOfMemoryError: Java heap space
	at java.base/java.util.HashMap.newNode(HashMap.java:1910)
	at java.base/java.util.HashMap.putVal(HashMap.java:638)
	at java.base/java.util.HashMap.put(HashMap.java:619)
	at java.base/java.util.HashSet.add(HashSet.java:230)
	at java.base/java.util.AbstractCollection.addAll(AbstractCollection.java:338)
	at jadx.core.codegen.NameGen.addNamesUsedInClass(NameGen.java:47)
	at jadx.core.codegen.NameGen.<init>(NameGen.java:29)
	at jadx.core.codegen.MethodGen.<init>(MethodGen.java:67)
	at jadx.core.codegen.ClassGen.addMethodCode(ClassGen.java:403)
	at jadx.core.codegen.ClassGen.addMethod(ClassGen.java:335)
	at jadx.core.codegen.ClassGen.lambda$addInnerClsAndMethods$3(ClassGen.java:301)
	at jadx.core.codegen.ClassGen$$Lambda/0x00000000111a0468.accept(Unknown Source)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:186)
	at java.base/java.util.stream.SortedOps$RefSortingSink$$Lambda/0x00000000111d0430.accept(Unknown Source)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1612)
	at java.base/java.util.stream.SortedOps$RefSortingSink.end(SortedOps.java:395)
	at java.base/java.util.stream.Sink$ChainedReference.end(Sink.java:261)
	at java.base/java.util.stream.ReferencePipeline$7$1FlatMap.end(ReferencePipeline.java:284)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:571)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:560)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:153)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:176)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:265)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:632)
	at jadx.core.codegen.ClassGen.addInnerClsAndMethods(ClassGen.java:297)
	at jadx.core.codegen.ClassGen.addClassBody(ClassGen.java:286)
	at jadx.core.codegen.ClassGen.addClassBody(ClassGen.java:270)
	at jadx.core.codegen.ClassGen.addClassCode(ClassGen.java:161)
	at jadx.core.codegen.ClassGen.makeClass(ClassGen.java:103)
	at jadx.core.codegen.CodeGen$$Lambda/0x000000001119d738.call(Unknown Source)
	at jadx.core.codegen.CodeGen.wrapCodeGen(CodeGen.java:45)

