// Copyright (c) 2023 Stockbit All rights reserved.

syntax = "proto3";

package financial.emitten.entity.v2;

option go_package = "go.stockbit.io/protos/gen/go/financial/emitten/entity/v2;entity";

enum Status {
  // buf:lint:ignore ENUM_ZERO_VALUE_SUFFIX
  STATUS_ACTIVE = 0;
  STATUS_SUSPENDED = 1;
  STATUS_DELISTED = 2;
}

enum StatusV2 {
  STATUS_V2_UNSPECIFIED = 0;
  STATUS_V2_ACTIVE = 1;
  STATUS_V2_SUSPENDED = 2;
  STATUS_V2_DELISTED = 3;
}

enum CompanyType {
  COMPANY_TYPE_UNSPECIFIED = 0;
  COMPANY_TYPE_SAHAM = 1;
  COMPANY_TYPE_INDEX = 2;
  COMPANY_TYPE_FX = 3;
  COMPANY_TYPE_ETF = 4;
  COMPANY_TYPE_INDEX_ASING = 5;
  COMPANY_TYPE_COMMODITIES = 6;
  COMPANY_TYPE_CRYPTO = 7;
  COMPANY_TYPE_WARAN = 8;
  COMPANY_TYPE_RIGHT = 9;
  COMPANY_TYPE_REKSADANA = 10;
}

message Stock {
  string change = 1;
  string symbol = 2;
  string percent = 3;
  string name = 4;
  string last = 5;
  string symbol_2 = 6 [json_name = "symbol_2"];
  string symbol_3 = 7 [json_name = "symbol_3"];
  string company_id = 8 [json_name = "company_id"];
  repeated Notation notation = 9;
  bool uma = 10;
  int32 tradeable = 11;
  string country = 12;
  string type = 13;
  CorpAction corp_action = 14 [json_name = "corp_action"];
  int32 isexist = 15;
  Status status = 16;
  string icon_url = 17 [json_name = "icon_url"];
  bool is_following = 18 [json_name = "is_following"];
  string formatted_price = 19 [json_name = "formatted_price"];
  bool is_exists = 21 [json_name = "is_exists"];
}

message CorpAction {
  bool active = 1;
  string icon = 2;
  string text = 3;
}

message Notation {
  string notation_code = 1 [json_name = "notation_code"];
  string notation_desc = 2 [json_name = "notation_desc"];
  IconURL icon_url = 3 [json_name = "icon_url"];
}

message IconURL {
  string light_mode = 1 [json_name = "light_mode"]; // ex: https://assets.stockbit.com/notations/light/X.png
  string dark_mode = 2 [json_name = "dark_mode"]; // ex: https://assets.stockbit.com/notations/dark/X.png
}

message CompanyPageInfo {
  string aum = 1;
  string average = 2;
  string change = 3;
  string country = 4;
  string created = 5;
  string date = 6;
  string exchange = 7;
  int32 followed = 8;
  int32 followers = 9;
  string id = 10;
  repeated string indexes = 11;
  string name = 12;
  OrderTrade orderbook = 13;
  float percentage = 14;
  string previous = 15;
  string price = 16;
  repeated string prices = 17;
  string sector = 18;
  Sentiments sentiment = 19;
  Status status = 20;
  string sub_sector = 21 [json_name = "sub_sector"];
  string symbol = 22;
  string symbol_2 = 23;
  string symbol_3 = 24;
  repeated string tabs = 25;
  string time = 26;
  int32 tradeable = 27;
  string type_company = 28 [json_name = "type_company"];
  string updated = 29;
  string value = 30;
  int64 volume = 31;
  MarketHour market_hour = 32 [json_name = "market_hour"];
  bool is_holding_exist = 33 [json_name = "is_holding_exist"];
  string formatted_price = 34 [json_name = "formatted_price"];
  bool is_price_alert_exist = 35 [json_name = "is_price_alert_exist"];
  repeated Notation notation = 36;
  string trade_type = 37 [json_name = "trade_type"];
  repeated Catalog catalogs = 38;
  repeated IndexesInfo indexes_data = 39 [json_name = "indexes_data"];
  string icon_url = 40 [json_name = "icon_url"];
  CorpAction corp_action = 41 [json_name = "corp_action"];
  bool uma = 42;
}

message Catalog {
  string company_symbol = 1 [json_name = "company_symbol"];
  string catalog_name = 2 [json_name = "catalog_name"];
  string id = 3;
  string parent = 4;
  string company_type = 5 [json_name = "company_type"];
}

message IndexesInfo {
  string company_symbol = 1 [json_name = "company_symbol"];
  string company_type = 2 [json_name = "company_type"];
}

message MarketHour {
  string status = 1;
  int32 time_left = 2 [json_name = "time_left"];
  string formatted_time_left = 3 [json_name = "formatted_time_left"];
  string suspend_info = 4 [json_name = "suspend_info"];
}
message OrderPriceVol {
  string price = 1;
  string volume = 2;
}

message OrderTrade {
  OrderPriceVol bid = 1;
  OrderPriceVol offer = 2;
}

message Sentiments {
  float end_value = 1 [json_name = "end_value"];
  string period = 2;
  float start_value = 3 [json_name = "start_value"];
  float value = 4;
}

message SectorCatalog {
  int32 company_id = 1 [json_name = "company_id"];
  string symbol = 2;
  string symbol_2 = 3 [json_name = "symbol_2"];
  string icon = 4;
  int32 total_stock = 5 [json_name = "total_stock"];
}

message PopularStock {
  int32 company_id = 1 [json_name = "company_id"];
  string symbol = 2;
  string symbol_2 = 3 [json_name = "symbol_2"];
  string symbol_3 = 4 [json_name = "symbol_3"];
  string name = 5;
  bool is_following = 6;
  bool is_exists = 7 [json_name = "is_exists"];
  string icon_url = 17 [json_name = "icon_url"];
}

message Company {
  string id = 1;
  string symbol = 2;
  string name = 3;
}

message SectorSubsectorCompany {
  string id = 1;
  string name = 2;
  string alias1 = 3;
  string parent = 4;
}

message CompanyInIndustry {
  string avgvolume = 1;
  string change = 2;
  string company_id = 3 [json_name = "company_id"];
  string country = 4;
  int32 followed = 5;
  int32 followers = 6;
  int32 isexist = 7;
  string last = 8;
  string marketcap = 9;
  string name = 10;
  int32 popularity = 11;
  string symbol = 12;
  string symbol_2 = 13 [json_name = "symbol_2"];
  string symbol_3 = 14 [json_name = "symbol_3"];
  int32 tradeable = 15;
  string type_company = 16 [json_name = "type_company"];
  int32 value = 17;
  string valuema20 = 18;
  int32 volume = 19;
  string icon_url = 20 [json_name = "icon_url"];
  string formatted_price = 21 [json_name = "formatted_price"];
  string percent = 22;
  bool is_exists = 23 [json_name = "is_exists"];
}

message ListDiscover {
  string company_id = 1 [json_name = "company_id"];
  string symbol = 2;
  string symbol_2 = 3 [json_name = "symbol_2"];
  string symbol_3 = 4 [json_name = "symbol_3"];
  string name = 5;
  string last = 6;
  string change = 7;
  string percent = 8;
  int32 isexist = 9;
  repeated Notation notation = 10;
  bool uma = 11;
  CorpAction corp_action = 12 [json_name = "corp_action"];
  bool is_exists = 13 [json_name = "is_exists"];
  string icon_url = 14 [json_name = "icon_url"];
}

message ListFinancialDiscover {
  int32 id = 1;
  string name = 2;
  repeated ListDiscover companies = 3;
}

message CompanyDetail {
  int32 company_id = 1 [json_name = "company_id"];
  string symbol = 2;
  string symbol_2 = 3 [json_name = "symbol_2"];
  string symbol_3 = 4 [json_name = "symbol_3"];
  string name = 5;
  string country = 6;
  string exchange = 7;
  string icon_url = 8 [json_name = "icon_url"];
}

message CompanyContact {
  string avatar = 1;
  string fullname = 2;
  string id = 3;
  int32 is_followed = 4 [json_name = "is_followed"];
  bool is_verified = 5;
  string thumb = 6;
  string username = 7;
}

message GetCompanyDataCatalog {
  string icon = 1;
  repeated string prices = 2;
  float previous = 3;
  float last = 4;
  string change = 5;
  float percent = 6;
  string type = 7;
  string symbol = 8;
  string symbol_2 = 9 [json_name = "symbol_2"];
  string id = 10;
}

message GetCompanyCatalog {
  repeated GetCompanyDataCatalog pchange_info = 1 [json_name = "pchange_info"];
}

message EmittenResult {
  int64 id = 1;
  string symbol = 2;
  string name = 3;
  string sector = 4;
  string subsector = 5;
  string profile = 6;
  string country = 7;
  string type = 8;
  string status_text = 9 [json_name = "status_text"];
  ShareOutstanding share_outstanding = 10 [json_name = "share_outstanding"];
}

message ShareOutstanding {
  string raw = 1;
  string formatted = 2;
}

message DetailCompany {
  int32 id = 1;
  Symbol symbol = 2;
  CompanyType type = 3;
  Sector sector = 4;
  Sector sub_sector = 5 [json_name = "sub_sector"];
  string name = 6;
  string profile = 7;
  string country = 8;
  StatusV2 status = 9;
  ShareOutstanding share_outstanding = 10 [json_name = "share_outstanding"];
}

message Sector {
  int32 id = 1;
  string name = 2;
}

message Symbol {
  string quote = 1; // equivalent symbol_1
  string ticker = 2; // equivalent symbol_2
  string code = 3; // equivalent symbol_3
}

message SectorCompanyResult {
  string id = 1;
  string name = 2;
  string alias1 = 3;
  string parent = 4;
}

message TypeCompanyResult {
  string name = 1;
}

message StatusCompanyResult {
  int64 id = 1;
  string name = 2;
}

message ListComponentCompany {
  repeated SectorCompanyResult sectors = 1;
  repeated CompanyType types = 2;
  repeated TypeCompanyResult countries = 3;
  repeated StatusV2 statuses = 4;
}
