syntax = "proto3";

package social.chat.entity.v2;

import "social/chat/entity/v2/message_content.proto";

option go_package = "go.stockbit.io/protos/gen/go/social/chat/entity/v2;entity";

message AttachmentMeta {
  oneof meta {
    PictureMeta picture = 1;
    DocumentMeta document = 2;
  }
}

message PictureMeta {
  int32 height = 1;
  int32 width = 2;
}

message DocumentMeta {
  // reserve for later
}

enum UploadType {
  UPLOAD_TYPE_UNSPECIFIED = 0;
  UPLOAD_TYPE_PICTURE = 1;
  UPLOAD_TYPE_DOCUMENT = 2;
  UPLOAD_TYPE_STICKER = 3;
}

message UploadAttachment {
  UploadType type = 1;
  string url = 2;
  string filename = 3;
  string size = 4;
  AttachmentMeta meta = 5;
}

enum AttachmentType {
  ATTACHMENT_TYPE_UNSPECIFIED = 0;
  ATTACHMENT_TYPE_UPLOADED = 1;
  ATTACHMENT_TYPE_SHARED = 2;
}

message AttachmentV2 {
  oneof attachment {
    UploadAttachment upload = 1;
    social.chat.entity.v2.SharedContentPreview shared = 2;
  }
}

message UploadAttachmentParam {
  UploadType type = 1;
  string url = 2;
}
