syntax = "proto3";

package social.chat.entity.v2;

import "social/chat/entity/v2/room.proto";
import "social/verified_badge/enum/v1/verified_status.proto";

option go_package = "go.stockbit.io/protos/gen/go/social/chat/entity/v2;entity";

message MemberUser {
  int32 user_id = 1;
  string username = 2;
  string full_name = 3;
  string avatar = 4;
  bool is_verified = 5;
  int32 member_id = 6;
  social.verified_badge.enum.v1.VerifiedStatus verified_status = 7;
}

enum MemberRole {
  MEMBER_ROLE_UNSPECIFIED = 0;
  MEMBER_ROLE_NORMAL = 1;
  MEMBER_ROLE_ADMIN = 2;
}

message GroupMember {
  MemberUser user = 1;
  MemberRole role = 2;
  social.chat.entity.v2.RoomState status = 3;
  bool is_interactable = 4;
}

message MemberUserData {
  MemberUser member_info = 1;
  bool is_group_member = 2;
}

message MemberStats {
  int32 capacity = 1;
  int32 current = 2;
  int32 available = 3;
  int32 active = 4;
}

message AdminStats {
  int32 total = 1;
}
