syntax = "proto3";

package social.chat.entity.v2;

import "google/protobuf/timestamp.proto";
import "social/stream/v1/stream.proto";

option go_package = "go.stockbit.io/protos/gen/go/social/chat/entity/v2;entity";

message Attachment {
  string url = 1;
  int32 height = 2;
  int32 width = 3;
  string filename = 4;
  string size = 5; // ex: 1.2 MB, 88 KB, ...
}

enum SharedContentType {
  SHARED_CONTENT_TYPE_UNSPECIFIED = 0;
  SHARED_CONTENT_TYPE_STREAM = 1;
  SHARED_CONTENT_TYPE_GROUP_INVITATION = 2;
  SHARED_CONTENT_TYPE_SHARETRADE = 3;
}

message SharedContentInternal {
  enum SourceType {
    SOURCE_TYPE_UNSPECIFIED = 0;
    SOURCE_TYPE_REFERENCE = 1;
    SOURCE_TYPE_PAYLOAD = 2;
  }
  message SourceData {
    oneof source {
      // need to fetch data for preview by reference_id
      SharedContent reference = 1;

      // preview created based on given payload
      SharedContentPayload payload = 2;
    }
  }

  SourceType source_type = 1;
  SourceData source_data = 2;
}

message SharedContent {
  SharedContentType type = 1;
  int32 id = 2;
}

message SharedContentPayload {
  enum Type {
    TYPE_UNSPECIFIED = 0;
    TYPE_SHARETRADE = 1;
  }
  message Payload {
    oneof data {
      ShareTradeInfo sharetrade = 1;
    }
  }
  Payload payload = 1;
}

message SharedContentPreview {
  SharedContentType type = 1;
  int32 id = 2;

  message Preview {
    oneof data {
      social.stream.v1.GetStreamOldResponse stream = 1;
      InvitationContentPreview invitation = 2;
      ShareTradeInfo sharetrade = 3;
    }
  }
  Preview preview = 3;
}

message InvitationContentPreview {
  string invitation_code = 1;
  string room_name = 2;
}

message ShareTradeInfo {
  string text = 1;

  string symbol = 2;

  enum OrderType {
    ORDER_TYPE_UNSPECIFIED = 0;
    ORDER_TYPE_BUY = 1;
    ORDER_TYPE_SELL = 2;
  }
  OrderType order_type = 3;

  enum OrderStatus {
    ORDER_STATUS_UNSPECIFIED = 0;
    ORDER_STATUS_OPEN = 1;
    ORDER_STATUS_AMEND = 2;
    ORDER_STATUS_CANCEL = 3;
    ORDER_STATUS_MATCH = 4;
    ORDER_STATUS_PARTIAL_MATCH = 5;
  }
  OrderStatus status = 4;

  enum UpdatedStatus {
    UPDATED_STATUS_UNSPECIFIED = 0;
    UPDATED_STATUS_AMENDED = 1;
    UPDATED_STATUS_CANCELLED = 2;
  }
  UpdatedStatus updated_status = 5;

  string price = 6;
  string updated_price = 7;
  string parent_order_id = 8;
  google.protobuf.Timestamp order_time = 9;

  enum Label {
    LABEL_UNSPECIFIED = 0;
    LABEL_DAY_TRADE = 1;
    LABEL_SPLIT_ORDER = 2;
  }
  Label label = 10;
  bool is_show_value = 11;
  int32 qty = 12;
  int32 updated_qty = 13;
  string total_investment = 14;
  bool is_amend_lot = 15;
}
