// Copyright (c) 2021-2024 Stockbit All rights reserved.

syntax = "proto3";

package social.chat.entity.v2;

import "google/protobuf/timestamp.proto";
import "social/chat/entity/v2/text_mask.proto";
import "social/verified_badge/enum/v1/verified_status.proto";

option go_package = "go.stockbit.io/protos/gen/go/social/chat/entity/v2;entity";

message RoomInfo {
  string name = 1;
  string shortened_name = 2;
  string description = 3;
  string avatar_url = 4;
}

message BaseRoom {
  int32 id = 1;
  RoomType type = 2;
  RoomInfo info = 3;
  RoomState state = 4;
}

message Room {
  int32 id = 1;
  RoomType type = 2;
  RoomInfo info = 3;
  RoomAttribute attributes = 4;

  // Deprecated: use unread_message instead
  int32 unread_count = 5 [deprecated = true];

  LastMessage last_message = 6;

  RoomStatus status = 7;
  RoomState state = 8;

  UnreadMessage unread_message = 9;
}

message UnreadMessage {
  int32 total = 1;
  int32 last_id = 2;
}

message LastMessage {
  enum AttachmentType {
    ATTACHMENT_TYPE_UNSPECIFIED = 0;
    ATTACHMENT_TYPE_PHOTO = 1;
    ATTACHMENT_TYPE_GIF = 2;
    ATTACHMENT_TYPE_POST = 3;
    ATTACHMENT_TYPE_SHARETRADE = 4;
    ATTACHMENT_TYPE_PDF = 5;
    ATTACHMENT_TYPE_STICKER = 6;
  }
  string text = 1;
  string sender_username = 2;
  AttachmentType type = 3;
  google.protobuf.Timestamp created_at = 4;
  bool is_deleted = 5;
  int32 id = 6;
  social.chat.entity.v2.PlaceholderMaskedText placeholder_mask = 7;
}

message RoomStatus {
  bool is_muted = 1;
  bool is_mentioned = 2;
}

enum RoomType {
  ROOM_TYPE_UNSPECIFIED = 0;
  ROOM_TYPE_PERSONAL = 1;
  ROOM_TYPE_GROUP = 2;
  ROOM_TYPE_BROADCAST = 3;
}

message RoomAttribute {
  oneof attr {
    PersonalRoomAttribute personal = 1;
    GroupRoomAttribute group = 2;
  }
}

message PersonalRoomAttribute {
  int32 user_id = 1;
  bool is_verified = 2;
  bool is_admin = 3;
  bool is_deactivated = 4;
  bool is_blocked = 5;
  social.verified_badge.enum.v1.VerifiedStatus verified_status = 6;
}

message GroupRoomAttribute {
  string member_description = 1;
}

enum RoomState {
  ROOM_STATE_UNSPECIFIED = 0;
  ROOM_STATE_ACCEPTED = 1;
  ROOM_STATE_INVITED = 2;
}
