syntax = "proto3";

package social.wssocial.entity.wsevent.chat.v1;

option go_package = "go.stockbit.io/protos/gen/go/social/wssocial/entity/wsevent/chat/v1;event";

message SendTypingIndicator {
  int32 room_id = 1;
  bool is_typing = 2;
}

message ReceivedTypingIndicator {
  ReceivedTypingIndicatorV1 v1 = 2;
}

message ReceivedTypingIndicatorV1 {
  int32 room_id = 1;
  message UserTypingInfo {
    int32 user_id = 1;
    string username = 2;
    string full_name = 3;
  }
  UserTypingInfo user = 2;
  bool is_typing = 3;
}
