syntax = "proto3";

package social.wssocial.entity.message.v1;

option go_package = "go.stockbit.io/protos/gen/go/social/wssocial/entity/message/v1;message";

message Channel {
  // Chatroom channel used for listen new event dedicated inside chatroom view
  // entity used for this channel are:
  // - social.wssocial.entity.wsevent.chat.v1.ReceivedMessage
  // - social.wssocial.entity.wsevent.chat.v1.SendTypingIndicator
  // - social.wssocial.entity.wsevent.chat.v1.ReceivedTypingIndicator
  repeated int32 chatroom = 1;

  // Roomlist channel used for listen new event in chatlist view
  // entity used for this channel:
  // - social.wssocial.entity.wsevent.chat.v1.ReceivedRoomInfo
  bool roomlist = 2;
}
