syntax = "proto3";

package social.wssocial.entity.message.v1;

import "social/wssocial/entity/message/v1/base.proto";
import "social/wssocial/entity/wsevent/chat/v1/typing_indicator.proto";

option go_package = "go.stockbit.io/protos/gen/go/social/wssocial/entity/message/v1;message";

message SendMessage {
  enum Type {
    TYPE_UNSPECIFIED = 0;
    TYPE_PING = 1;
    TYPE_SUBSCRIBE = 2;
    TYPE_UNSUBSCRIBE = 3;
    // broadcast type is used for sending and receiving event message
    TYPE_BROADCAST = 4;
  }

  Type type = 1;
  Payload payload = 2;
}

message Payload {
  oneof payload {
    Channel channel = 1;
    SendEvent event = 2;
  }
  // reserved for possible future fields outside oneof to avoid field number conflict
  reserved 10 to 20;
}

message SendEvent {
  enum Type {
    TYPE_UNSPECIFIED = 0;
    TYPE_CHAT_TYPING_INDICATOR = 1;
  }
  Type type = 1;

  message Data {
    oneof data {
      social.wssocial.entity.wsevent.chat.v1.SendTypingIndicator chat_typing_indicator = 1;
    }
    // reserved for possible future fields outside oneof to avoid field number conflict
    reserved 20 to 30;
  }
  Data data = 2;
}
