syntax = "proto3";

package securities.transactional.datafeed.v1;

option java_package = "com.stockbit.protobuf.securities.transactional.datafeed.v1.datafeed";
option java_multiple_files = true;
message Bid {
  double price = 1;
  double lot = 2;
}

message Offer {
  double price = 1;
  double lot = 2;
}

message Change {
  double value = 1;
  double percentage = 2;
}

enum Top20Type {
  TOP20_TYPE_UNSPECIFIED = 0;
  TOP20_TYPE_FREQUENCY_RG = 2;
  TOP20_TYPE_PERCENTAGE_GAINER_RG = 5;
  TOP20_TYPE_PERCENTAGE_LOSER_RG = 6;
}
enum ErrorCode {
  ERROR_CODE_UNSPECIFIED = 0;
  ERROR_CODE_BAD_REQUEST = 400;
  ERROR_CODE_UNAUTHORIZED = 401;
}

message Error {
  ErrorCode code = 1;
  string message = 2;
}

enum TradeType {
  TRADE_TYPE_UNSPECIFIED = 0;
  TRADE_TYPE_BUY = 1;
  TRADE_TYPE_SELL = 2;
}
