syntax = "proto3";

package securities.transactional.datafeed.v1;

import "google/protobuf/timestamp.proto";
import "securities/transactional/datafeed/consumer/entity/v1/entity.proto";
import "securities/transactional/datafeed/v1/entity.proto";

option java_package = "com.stockbit.protobuf.securities.transactional.datafeed.v1.datafeed";
option java_multiple_files = true;

message RunningTrade {
  google.protobuf.Timestamp websocket_time = 1 [json_name = "websocket_time"];
  string stock = 2;
  double price = 3;
  double volume = 4;
  securities.transactional.datafeed.v1.TradeType action = 5;
  bool is_global = 6 [json_name = "is_global"];
  google.protobuf.Timestamp time = 7;
  securities.transactional.datafeed.v1.Change change = 8;
  int32 trade_number = 9 [json_name = "trade_number"];
  securities.transactional.datafeed.consumer.entity.v1.BoardType market_board = 10;
  double value = 11;
}

message RunningTradeBatch {
  repeated RunningTrade batch = 1;
}
