// Copyright (c) 2021-2024 Stockbit All rights reserved.

syntax = "proto3";

package securities.transactional.datafeed.v1;

import "financial/order_trade/entity/v1/order_queue.proto";
import "securities/transactional/datafeed/v1/hotlist.proto";
import "securities/transactional/datafeed/v1/orderbook.proto";
import "securities/transactional/datafeed/v1/ping.proto";
import "securities/transactional/datafeed/v1/running_trade.proto";
import "securities/transactional/datafeed/v1/watchlist.proto";
import "securities/transactional/datafeed/v1/iep_iev.proto";
import "securities/transactional/datafeed/v1/entity.proto";
import "securities/transactional/datafeed/v1/best_bid_offer.proto";
import "securities/transactional/datafeed/consumer/entity/v1/entity.proto";
import "financial/order_trade/entity/v1/market_mover.proto";
import "financial/company_price_feed/entity/v2/indicative_price_volume.proto";
import "securities/transactional/datafeed/consumer/entity/v3/orderbook.proto";
import "securities/transactional/datafeed/consumer/entity/v3/liveprice.proto";

option java_package = "com.stockbit.protobuf.securities.transactional.datafeed.v1.datafeed";
option java_multiple_files = true;

message WebsocketRequest {
  string user_id = 1 [json_name = "user_id"];
  WebsocketChannel channel = 2;
  string key = 3;
  securities.transactional.datafeed.v1.PingRequest ping = 4;
  string access_token = 5 [json_name = "access_token"];
}

message WebsocketChannel {
  repeated string watchlist = 1;
  repeated string order_book = 2 [json_name = "order_book"];
  repeated string running_trade = 3 [json_name = "running_trade"];
  bool is_hotlist = 4 [json_name = "is_hotlist"];
  repeated string running_trade_batch = 5 [json_name = "running_trade_batch"];
  repeated string liveprice = 6 [json_name = "liveprice"];
  repeated string iepiev = 7 [json_name = "iepiev"];
  repeated string intraday = 8 [json_name = "intraday"];
  repeated string best_bid_offer = 9 [json_name = "best_bid_offer"];
  repeated financial.order_trade.entity.v1.MarketMoverWebsocketRequest market_mover = 10 [json_name = "market_mover"];
  repeated financial.order_trade.entity.v1.OrderQueueWebsocketRequest order_queue = 11 [json_name = "order_queue"];
  repeated string liveprice_v3 = 12 [json_name = "liveprice_v3"];
  repeated string order_book_v3 = 13 [json_name = "order_book_v3"];
}

message WebsocketWrapMessageChannel {
  oneof message_channel {
    securities.transactional.datafeed.v1.RunningTrade running_trade = 1 [json_name = "running_trade"];
    securities.transactional.datafeed.v1.PingResponse ping = 2;
    securities.transactional.datafeed.v1.Top20 top20 = 3;
    securities.transactional.datafeed.v1.Watchlist watchlist = 4;
    securities.transactional.datafeed.v1.OrderBookHeader orderbook_header = 5 [json_name = "orderbook_header"];
    securities.transactional.datafeed.v1.OrderBookBody orderbook_body = 6 [json_name = "orderbook_body"];
    securities.transactional.datafeed.v1.Error error = 7;
    securities.transactional.datafeed.v1.RunningTradeBatch running_trade_batch = 8 [json_name = "running_trade_batch"];
    securities.transactional.datafeed.consumer.entity.v1.LivePrice liveprice = 9;
    securities.transactional.datafeed.consumer.entity.v1.Orderbook orderbook = 10;
    financial.company_price_feed.entity.v2.IEPIEV iepiev = 11;
    securities.transactional.datafeed.consumer.entity.v1.Intraday intraday = 12;
    securities.transactional.datafeed.v1.BestBidOfferWS best_bid_offer = 13 [json_name = "best_bid_offer"];
    financial.order_trade.entity.v1.MarketMoverBatch market_mover_batch = 14 [json_name = "market_mover_batch"];
    financial.order_trade.entity.v1.OrderQueueWebsocket order_queue = 15 [json_name = "order_queue"];
    securities.transactional.datafeed.consumer.entity.v3.LivePrice liveprice_v3 = 16 [json_name = "liveprice_v3"];
    securities.transactional.datafeed.consumer.entity.v3.Orderbook orderbook_v3 = 17 [json_name = "orderbook_v3"];
  }
}